import React, {useMemo, useState} from 'react';
import {Alert, I18nManager, Modal, Pressable, SafeAreaView, ScrollView, StatusBar, StyleSheet, Text, TextInput, TouchableOpacity, View} from 'react-native';
import {colors, shadow} from './src/theme';

I18nManager.allowRTL(true);
const money=n=>`${Number(n||0).toLocaleString('ar-JO')} د.أ`;
const months=['كانون الثاني','شباط','آذار','نيسان','أيار','حزيران','تموز','آب','أيلول','تشرين الأول','تشرين الثاني','كانون الأول'];
const tabs=[['home','⌂','الرئيسية'],['residents','♙','السكان'],['cars','▱','السيارات'],['orders','▤','الطلبات'],['expenses','◫','المصاريف']];
const buildings=[{id:'b1',name:'عمارة الياسمين',area:'الجبيهة، عمّان',units:8},{id:'b2',name:'برج النخيل',area:'شارع الجامعة، عمّان',units:6},{id:'b3',name:'مساكن الروابي',area:'تلاع العلي، عمّان',units:5}];
const initialResidents=[
 {id:'r1',buildingId:'b1',name:'ساكن شقة 101',owner:'مالك تجريبي 1',phone:'',unit:'101',monthly:50,paid:50,car:true,plate:'تجريبي-101',parking:'4'},
 {id:'r2',buildingId:'b1',name:'ساكن شقة 102',owner:'مالك تجريبي 2',phone:'',unit:'102',monthly:50,paid:25,car:true,plate:'تجريبي-102',parking:''},
 {id:'r3',buildingId:'b1',name:'ساكن شقة 201',owner:'مالك تجريبي 3',phone:'',unit:'201',monthly:50,paid:0,car:false,plate:'',parking:''},
 {id:'r4',buildingId:'b1',name:'ساكن شقة 202',owner:'مالك تجريبي 4',phone:'',unit:'202',monthly:45,paid:45,car:true,plate:'تجريبي-202',parking:'7'},
 {id:'r5',buildingId:'b2',name:'ساكن شقة 2',owner:'مالك تجريبي 5',phone:'',unit:'2',monthly:40,paid:0,car:true,plate:'تجريبي-2',parking:'2'},
 {id:'r6',buildingId:'b3',name:'ساكن شقة 3',owner:'مالك تجريبي 6',phone:'',unit:'3',monthly:35,paid:35,car:false,plate:'',parking:''}
];
const initialOrders=[{id:'o1',buildingId:'b1',resident:'ساكن شقة 102',type:'خضار وفواكه',items:'طماطم 2 كغم، خيار، موز',total:12.5,status:'جديد'},{id:'o2',buildingId:'b1',resident:'ساكن شقة 202',type:'سوبرماركت',items:'حليب، خبز، سكر',total:8.75,status:'جارٍ الشراء'},{id:'o3',buildingId:'b2',resident:'ساكن شقة 2',type:'مخبز',items:'خبز عربي × 3',total:1.5,status:'تم التسليم'}];
const initialExpenses=[{id:'e1',buildingId:'b1',type:'صيانة المصعد',note:'فحص دوري وتزييت',amount:45,date:'12 أيلول'},{id:'e2',buildingId:'b1',type:'تصليحات',note:'تصليح قفل باب المدخل',amount:18,date:'8 أيلول'},{id:'e3',buildingId:'b2',type:'مصروف آخر',note:'نسخة مفاتيح',amount:7,date:'5 أيلول'}];

function Brand(){return <View style={s.brand}><View style={s.logo}><Text style={s.logoText}>د</Text><View style={s.check}><Text style={s.checkText}>✓</Text></View></View><View><Text style={s.brandName}>دَوْرَك</Text><Text style={s.brandSub}>كل عماراتك بإدارة واحدة</Text></View></View>}
function Button({label,onPress,small}){return <TouchableOpacity onPress={onPress} style={[s.button,small&&s.buttonSmall]}><Text style={s.buttonText}>{label}</Text></TouchableOpacity>}
function Badge({status}){const tone=status==='مدفوع'||status==='تم التسليم'?'green':status==='جزئي'||status==='جارٍ الشراء'?'orange':status==='جديد'?'blue':'red';return <View style={[s.badge,{backgroundColor:colors[`${tone}Soft`]||colors.primarySoft}]}><Text style={[s.badgeText,{color:colors[tone]}]}>{status}</Text></View>}
function Card({children,style}){return <View style={[s.card,style]}>{children}</View>}
function PageTitle({title,sub,action,onAction}){return <View style={s.pageTitle}><View style={{flex:1}}><Text style={s.title}>{title}</Text><Text style={s.muted}>{sub}</Text></View>{action&&<Button label={action} small onPress={onAction}/>}</View>}
function Field({label,value,onChangeText,placeholder,keyboardType}){return <View style={s.field}><Text style={s.fieldLabel}>{label}</Text><TextInput value={String(value??'')} onChangeText={onChangeText} placeholder={placeholder} placeholderTextColor={colors.muted} keyboardType={keyboardType} style={s.input} textAlign="right"/></View>}
function Empty({text}){return <View style={s.empty}><Text style={s.emptyIcon}>□</Text><Text style={s.muted}>{text}</Text></View>}

function Header({building,onOpen}){return <View style={s.header}><Brand/><TouchableOpacity onPress={onOpen} style={s.buildingPicker}><View style={{flex:1}}><Text style={s.pickerLabel}>العمارة الحالية</Text><Text style={s.pickerName}>{building.name}  ⌄</Text></View><View style={s.buildingIcon}><Text style={s.primaryIcon}>▥</Text></View></TouchableOpacity></View>}
function MonthBar({month,setMonth}){const move=n=>setMonth(d=>new Date(d.getFullYear(),d.getMonth()+n,1));return <View style={s.monthBar}><TouchableOpacity onPress={()=>move(1)} style={s.circleBtn}><Text style={s.arrow}>‹</Text></TouchableOpacity><View><Text style={s.monthTitle}>{months[month.getMonth()]} {month.getFullYear()}</Text><Text style={s.monthHint}>السجل الشهري</Text></View><TouchableOpacity onPress={()=>move(-1)} style={s.circleBtn}><Text style={s.arrow}>›</Text></TouchableOpacity></View>}
function Summary({residents,expenses}){const required=residents.reduce((a,r)=>a+Number(r.monthly),0),paid=residents.reduce((a,r)=>a+Number(r.paid),0),spent=expenses.reduce((a,e)=>a+Number(e.amount),0);return <View style={s.summaryGrid}><View style={[s.summary,s.summaryPrimary]}><Text style={s.summaryLight}>المحصّل</Text><Text style={s.summaryBigLight}>{money(paid)}</Text><Text style={s.summaryFootLight}>من أصل {money(required)}</Text></View><View style={s.summary}><Text style={s.summaryLabel}>المتبقي</Text><Text style={[s.summaryBig,{color:colors.red}]}>{money(required-paid)}</Text><Text style={s.summaryFoot}>{residents.filter(r=>r.paid<r.monthly).length} شقق</Text></View><View style={s.summary}><Text style={s.summaryLabel}>المصاريف</Text><Text style={s.summaryBig}>{money(spent)}</Text><Text style={s.summaryFoot}>الرصيد {money(paid-spent)}</Text></View></View>}

function ResidentRow({resident,onPress}){const status=resident.paid>=resident.monthly?'مدفوع':resident.paid>0?'جزئي':'متأخر';return <TouchableOpacity disabled={!onPress} onPress={onPress} style={s.personRow}><View style={s.personAvatar}><Text style={s.personAvatarText}>{resident.unit}</Text></View><View style={{flex:1}}><Text style={s.personName}>{resident.name}</Text><Text style={s.personMeta}>شقة {resident.unit} · المطلوب {money(resident.monthly)}</Text></View><View style={{alignItems:'flex-start'}}><Badge status={status}/><Text style={s.paidText}>{money(resident.paid)}</Text></View></TouchableOpacity>}
function Home({residents,expenses,month,setMonth,onResidents}){return <ScrollView contentContainerStyle={s.page}><View style={s.welcome}><View><Text style={s.hello}>أهلًا أحمد 👋</Text><Text style={s.muted}>هذا ملخص العمارة لهذا الشهر</Text></View><View style={s.avatar}><Text style={s.avatarText}>أ</Text></View></View><MonthBar month={month} setMonth={setMonth}/><Summary residents={residents} expenses={expenses}/><View style={s.sectionHead}><Text style={s.sectionTitle}>تحصيل السكان</Text><TouchableOpacity onPress={onResidents}><Text style={s.link}>عرض الكل</Text></TouchableOpacity></View>{residents.slice(0,5).map(r=><ResidentRow key={r.id} resident={r}/>) }<Card style={s.tip}><Text style={s.tipIcon}>💡</Text><View style={{flex:1}}><Text style={s.tipTitle}>السنوات محفوظة تلقائيًا</Text><Text style={s.tipText}>عند بدء سنة جديدة يظهر سجل شهري جديد، وتبقى أسماء السكان والسجلات السابقة محفوظة.</Text></View></Card></ScrollView>}
function Residents({residents,setResidents,onAdd}){const [q,setQ]=useState('');const list=residents.filter(r=>`${r.name} ${r.unit} ${r.owner}`.includes(q));const collect=r=>Alert.alert('تسجيل دفعة',`${r.name} — المتبقي ${money(r.monthly-r.paid)}`,[{text:'إلغاء',style:'cancel'},{text:'دفع كامل',onPress:()=>setResidents(all=>all.map(x=>x.id===r.id?{...x,paid:x.monthly}:x))},{text:'دفع 25 د.أ',onPress:()=>setResidents(all=>all.map(x=>x.id===r.id?{...x,paid:Math.min(Number(x.monthly),Number(x.paid)+25)}:x))}]);return <ScrollView contentContainerStyle={s.page}><PageTitle title="السكان والتحصيل" sub={`${residents.length} سكان في العمارة`} action="+ إضافة ساكن" onAction={onAdd}/><View style={s.search}><Text>⌕</Text><TextInput value={q} onChangeText={setQ} placeholder="ابحث بالاسم أو رقم الشقة" placeholderTextColor={colors.muted} style={s.searchInput} textAlign="right"/></View>{list.map(r=><ResidentRow key={r.id} resident={r} onPress={()=>collect(r)}/>)}<Text style={s.help}>اضغط على اسم الساكن لتسجيل الدفعة.</Text></ScrollView>}
function Cars({residents}){const cars=residents.filter(r=>r.car);return <ScrollView contentContainerStyle={s.page}><PageTitle title="السيارات" sub={`${cars.length} سيارات مسجلة`}/>{cars.map(r=><Card key={r.id} style={s.carCard}><View style={s.carIcon}><Text style={{fontSize:25}}>▱</Text></View><View style={{flex:1}}><Text style={s.personName}>{r.name}</Text><Text style={s.personMeta}>شقة {r.unit}</Text><Text style={s.plate}>{r.plate||'رقم اللوحة غير مسجل'}</Text></View><View><Text style={s.parkingLabel}>رقم الموقف</Text><Text style={s.parking}>{r.parking||'اختياري'}</Text></View></Card>)}{!cars.length&&<Empty text="لا توجد سيارات مسجلة"/>}</ScrollView>}
function Orders({orders,setOrders,onAdd}){const advance=o=>{const status=o.status==='جديد'?'جارٍ الشراء':'تم التسليم';setOrders(all=>all.map(x=>x.id===o.id?{...x,status}:x))};return <ScrollView contentContainerStyle={s.page}><PageTitle title="طلبات السكان" sub="سوبرماركت، خضار، فواكه ومخبز" action="+ طلب جديد" onAction={onAdd}/>{orders.map(o=><Card key={o.id} style={s.orderCard}><View style={s.orderTop}><Badge status={o.status}/><Text style={s.orderType}>{o.type}</Text></View><Text style={s.personName}>{o.resident}</Text><Text style={s.orderItems}>{o.items}</Text><View style={s.orderBottom}><Text style={s.orderTotal}>{money(o.total)}</Text>{o.status!=='تم التسليم'&&<Button label={o.status==='جديد'?'ابدأ الشراء':'تم التسليم'} small onPress={()=>advance(o)}/>}</View></Card>)}{!orders.length&&<Empty text="لا توجد طلبات لهذه العمارة"/>}</ScrollView>}
function Expenses({expenses,onAdd}){return <ScrollView contentContainerStyle={s.page}><PageTitle title="مصاريف العمارة" sub="صيانة المصعد، التصليحات ومصروف آخر" action="+ تسجيل مصروف" onAction={onAdd}/><Card style={s.expenseTotal}><Text style={s.summaryLabel}>إجمالي مصاريف الشهر</Text><Text style={s.expenseBig}>{money(expenses.reduce((a,e)=>a+Number(e.amount),0))}</Text></Card>{expenses.map(e=><View key={e.id} style={s.expenseRow}><View style={s.expenseIcon}><Text style={{color:colors.primary}}>◫</Text></View><View style={{flex:1}}><Text style={s.personName}>{e.type}</Text><Text style={s.personMeta}>{e.note} · {e.date}</Text></View><Text style={s.expenseAmount}>-{money(e.amount)}</Text></View>)}{!expenses.length&&<Empty text="لا توجد مصاريف مسجلة"/>}</ScrollView>}

function Sheet({visible,title,onClose,children}){return <Modal visible={visible} transparent animationType="slide" onRequestClose={onClose}><Pressable style={s.shade} onPress={onClose}/><View style={s.sheet}><View style={s.sheetHandle}/><View style={s.sheetHead}><TouchableOpacity onPress={onClose}><Text style={s.close}>×</Text></TouchableOpacity><Text style={s.sheetTitle}>{title}</Text></View><ScrollView keyboardShouldPersistTaps="handled">{children}</ScrollView></View></Modal>}
function BuildingSheet({visible,current,onChoose,onClose}){return <Sheet visible={visible} title="اختر العمارة" onClose={onClose}>{buildings.map(b=><TouchableOpacity key={b.id} onPress={()=>{onChoose(b.id);onClose()}} style={[s.chooseRow,b.id===current&&s.chooseActive]}><View style={s.buildingIcon}><Text style={s.primaryIcon}>▥</Text></View><View style={{flex:1}}><Text style={s.personName}>{b.name}</Text><Text style={s.personMeta}>{b.area} · {b.units} شقق</Text></View>{b.id===current&&<Text style={s.selected}>✓</Text>}</TouchableOpacity>)}</Sheet>}
function ResidentForm({visible,buildingId,onClose,onSave}){const blank={name:'',owner:'',phone:'',unit:'',monthly:'50',car:false,plate:'',parking:''},[d,setD]=useState(blank);const save=()=>{if(!d.name.trim()||!d.unit.trim())return Alert.alert('بيانات ناقصة','اكتب اسم الساكن ورقم الشقة');onSave({...d,id:`r${Date.now()}`,buildingId,paid:0,monthly:Number(d.monthly)||0});setD(blank);onClose()};return <Sheet visible={visible} title="إضافة ساكن" onClose={onClose}><Field label="اسم الساكن" value={d.name} onChangeText={v=>setD({...d,name:v})}/><Field label="اسم مالك الشقة" value={d.owner} onChangeText={v=>setD({...d,owner:v})} placeholder="يمكن أن يكون نفس الساكن"/><Field label="رقم الهاتف (اختياري)" value={d.phone} onChangeText={v=>setD({...d,phone:v})} keyboardType="phone-pad"/><View style={s.fieldsRow}><Field label="رقم الشقة" value={d.unit} onChangeText={v=>setD({...d,unit:v})}/><Field label="الاشتراك الشهري" value={d.monthly} onChangeText={v=>setD({...d,monthly:v})} keyboardType="numeric"/></View><TouchableOpacity onPress={()=>setD({...d,car:!d.car})} style={s.toggleRow}><Text style={s.personName}>لديه سيارة</Text><View style={[s.toggle,d.car&&s.toggleOn]}><View style={[s.knob,d.car&&s.knobOn]}/></View></TouchableOpacity>{d.car&&<><Field label="رقم اللوحة" value={d.plate} onChangeText={v=>setD({...d,plate:v})}/><Field label="رقم الموقف (اختياري)" value={d.parking} onChangeText={v=>setD({...d,parking:v})}/></>}<Button label="حفظ الساكن" onPress={save}/></Sheet>}
function Chips({values,selected,onSelect}){return <View style={s.chips}>{values.map(x=><TouchableOpacity key={x} onPress={()=>onSelect(x)} style={[s.chip,selected===x&&s.chipActive]}><Text style={[s.chipText,selected===x&&s.chipTextActive]}>{x}</Text></TouchableOpacity>)}</View>}
function OrderForm({visible,buildingId,residents,onClose,onSave}){const blank={resident:'',type:'سوبرماركت',items:'',total:''},[d,setD]=useState(blank);const save=()=>{if(!d.resident||!d.items.trim())return Alert.alert('بيانات ناقصة','اختر الساكن واكتب الطلب');onSave({...d,id:`o${Date.now()}`,buildingId,total:Number(d.total)||0,status:'جديد'});setD(blank);onClose()};return <Sheet visible={visible} title="طلب مشتريات جديد" onClose={onClose}><Text style={s.fieldLabel}>الساكن</Text><Chips values={residents.map(r=>r.name)} selected={d.resident} onSelect={x=>setD({...d,resident:x})}/><Text style={s.fieldLabel}>القسم</Text><Chips values={['سوبرماركت','خضار وفواكه','مخبز']} selected={d.type} onSelect={x=>setD({...d,type:x})}/><Field label="تفاصيل الطلب" value={d.items} onChangeText={v=>setD({...d,items:v})}/><Field label="المبلغ" value={d.total} onChangeText={v=>setD({...d,total:v})} keyboardType="decimal-pad"/><Button label="حفظ الطلب" onPress={save}/></Sheet>}
function ExpenseForm({visible,buildingId,onClose,onSave}){const blank={type:'صيانة المصعد',note:'',amount:''},[d,setD]=useState(blank);const save=()=>{if(!d.note.trim()||!Number(d.amount))return Alert.alert('بيانات ناقصة','اكتب الوصف والمبلغ');onSave({...d,id:`e${Date.now()}`,buildingId,amount:Number(d.amount),date:'اليوم'});setD(blank);onClose()};return <Sheet visible={visible} title="تسجيل مصروف" onClose={onClose}><Text style={s.fieldLabel}>نوع المصروف</Text><Chips values={['صيانة المصعد','تصليحات','مصروف آخر']} selected={d.type} onSelect={x=>setD({...d,type:x})}/><Field label="الوصف" value={d.note} onChangeText={v=>setD({...d,note:v})}/><Field label="المبلغ بالدينار" value={d.amount} onChangeText={v=>setD({...d,amount:v})} keyboardType="decimal-pad"/><Button label="حفظ المصروف" onPress={save}/></Sheet>}

export default function App(){const [tab,setTab]=useState('home'),[buildingId,setBuildingId]=useState('b1'),[month,setMonth]=useState(new Date()),[residents,setResidents]=useState(initialResidents),[orders,setOrders]=useState(initialOrders),[expenses,setExpenses]=useState(initialExpenses),[buildingSheet,setBuildingSheet]=useState(false),[residentForm,setResidentForm]=useState(false),[orderForm,setOrderForm]=useState(false),[expenseForm,setExpenseForm]=useState(false);const building=buildings.find(b=>b.id===buildingId),rs=useMemo(()=>residents.filter(r=>r.buildingId===buildingId),[residents,buildingId]),os=useMemo(()=>orders.filter(o=>o.buildingId===buildingId),[orders,buildingId]),es=useMemo(()=>expenses.filter(e=>e.buildingId===buildingId),[expenses,buildingId]);const pages={home:<Home residents={rs} expenses={es} month={month} setMonth={setMonth} onResidents={()=>setTab('residents')}/>,residents:<Residents residents={rs} setResidents={setResidents} onAdd={()=>setResidentForm(true)}/>,cars:<Cars residents={rs}/>,orders:<Orders orders={os} setOrders={setOrders} onAdd={()=>setOrderForm(true)}/>,expenses:<Expenses expenses={es} onAdd={()=>setExpenseForm(true)}/>};return <SafeAreaView style={s.safe}><StatusBar barStyle="dark-content" backgroundColor={colors.white}/><Header building={building} onOpen={()=>setBuildingSheet(true)}/><View style={{flex:1}}>{pages[tab]}</View><View style={s.bottomNav}>{tabs.map(t=><TouchableOpacity key={t[0]} onPress={()=>setTab(t[0])} style={s.tab}><Text style={[s.tabIcon,tab===t[0]&&s.tabActive]}>{t[1]}</Text><Text style={[s.tabText,tab===t[0]&&s.tabActive]}>{t[2]}</Text></TouchableOpacity>)}</View><BuildingSheet visible={buildingSheet} current={buildingId} onChoose={setBuildingId} onClose={()=>setBuildingSheet(false)}/><ResidentForm visible={residentForm} buildingId={buildingId} onClose={()=>setResidentForm(false)} onSave={r=>setResidents(a=>[r,...a])}/><OrderForm visible={orderForm} buildingId={buildingId} residents={rs} onClose={()=>setOrderForm(false)} onSave={o=>setOrders(a=>[o,...a])}/><ExpenseForm visible={expenseForm} buildingId={buildingId} onClose={()=>setExpenseForm(false)} onSave={e=>setExpenses(a=>[e,...a])}/></SafeAreaView>}

const s=StyleSheet.create({
 safe:{flex:1,backgroundColor:colors.white},header:{backgroundColor:colors.white,paddingHorizontal:18,paddingTop:9,paddingBottom:12,borderBottomWidth:1,borderBottomColor:colors.line},brand:{flexDirection:'row-reverse',alignItems:'center',gap:10,marginBottom:12},logo:{width:42,height:42,borderRadius:14,backgroundColor:colors.primary,alignItems:'center',justifyContent:'center'},logoText:{fontSize:25,fontWeight:'900',color:colors.white},check:{position:'absolute',right:-2,bottom:-2,width:16,height:16,borderRadius:8,backgroundColor:colors.green,borderWidth:2,borderColor:colors.white,alignItems:'center'},checkText:{fontSize:9,color:colors.white,fontWeight:'900'},brandName:{fontSize:19,fontWeight:'900',color:colors.primary,textAlign:'right'},brandSub:{fontSize:9.5,color:colors.muted,textAlign:'right'},buildingPicker:{height:56,backgroundColor:colors.canvas,borderRadius:15,paddingHorizontal:13,flexDirection:'row-reverse',alignItems:'center',gap:10},pickerLabel:{fontSize:9.5,color:colors.muted,textAlign:'right'},pickerName:{fontSize:14,fontWeight:'900',color:colors.text,textAlign:'right',marginTop:3},buildingIcon:{width:37,height:37,borderRadius:11,backgroundColor:colors.primarySoft,alignItems:'center',justifyContent:'center'},primaryIcon:{color:colors.primary,fontSize:20},
 page:{padding:16,paddingBottom:102},welcome:{flexDirection:'row-reverse',alignItems:'center',justifyContent:'space-between',marginBottom:14},hello:{fontSize:22,fontWeight:'900',color:colors.text,textAlign:'right'},muted:{fontSize:11.5,color:colors.muted,textAlign:'right',marginTop:4},avatar:{width:42,height:42,borderRadius:14,backgroundColor:colors.primarySoft,alignItems:'center',justifyContent:'center'},avatarText:{fontSize:17,color:colors.primary,fontWeight:'900'},monthBar:{height:63,backgroundColor:colors.white,borderRadius:17,flexDirection:'row-reverse',alignItems:'center',justifyContent:'space-between',paddingHorizontal:12,marginBottom:14,...shadow},circleBtn:{width:35,height:35,borderRadius:12,backgroundColor:colors.canvas,alignItems:'center',justifyContent:'center'},arrow:{fontSize:27,color:colors.primary},monthTitle:{fontSize:15,fontWeight:'900',color:colors.text,textAlign:'center'},monthHint:{fontSize:9.5,color:colors.muted,textAlign:'center',marginTop:2},summaryGrid:{flexDirection:'row-reverse',gap:9,marginBottom:21},summary:{flex:1,backgroundColor:colors.white,borderRadius:16,padding:12,...shadow},summaryPrimary:{backgroundColor:colors.primary},summaryLabel:{fontSize:10,color:colors.muted,textAlign:'right'},summaryLight:{fontSize:10,color:'#CBE1E6',textAlign:'right'},summaryBig:{fontSize:17,fontWeight:'900',color:colors.text,textAlign:'right',marginTop:6},summaryBigLight:{fontSize:17,fontWeight:'900',color:colors.white,textAlign:'right',marginTop:6},summaryFoot:{fontSize:8.5,color:colors.muted,textAlign:'right',marginTop:7},summaryFootLight:{fontSize:8.5,color:'#CBE1E6',textAlign:'right',marginTop:7},sectionHead:{flexDirection:'row-reverse',justifyContent:'space-between',marginBottom:10},sectionTitle:{fontSize:17,fontWeight:'900',color:colors.text},link:{fontSize:11,color:colors.primary,fontWeight:'800'},
 card:{backgroundColor:colors.white,borderRadius:17,padding:15,marginBottom:10,...shadow},personRow:{minHeight:76,backgroundColor:colors.white,borderRadius:16,padding:12,marginBottom:9,flexDirection:'row-reverse',alignItems:'center',gap:10,...shadow},personAvatar:{width:42,height:42,borderRadius:13,backgroundColor:colors.primarySoft,alignItems:'center',justifyContent:'center'},personAvatarText:{fontSize:12,color:colors.primary,fontWeight:'900'},personName:{fontSize:13.5,color:colors.text,fontWeight:'900',textAlign:'right'},personMeta:{fontSize:10.5,color:colors.muted,textAlign:'right',marginTop:4},paidText:{fontSize:10.5,color:colors.text,fontWeight:'800',marginTop:5},badge:{borderRadius:20,paddingHorizontal:9,paddingVertical:5},badgeText:{fontSize:9.5,fontWeight:'900'},tip:{flexDirection:'row-reverse',gap:10,backgroundColor:colors.primarySoft,marginTop:8},tipIcon:{fontSize:20},tipTitle:{fontSize:12.5,fontWeight:'900',color:colors.primary,textAlign:'right'},tipText:{fontSize:10.5,color:colors.muted,textAlign:'right',lineHeight:17,marginTop:4},
 pageTitle:{flexDirection:'row-reverse',alignItems:'center',gap:9,marginBottom:14},title:{fontSize:21,fontWeight:'900',color:colors.text,textAlign:'right'},button:{minHeight:44,borderRadius:13,backgroundColor:colors.primary,paddingHorizontal:17,alignItems:'center',justifyContent:'center',marginTop:8},buttonSmall:{minHeight:36,paddingHorizontal:11,marginTop:0},buttonText:{fontSize:11,fontWeight:'900',color:colors.white},search:{height:46,backgroundColor:colors.white,borderWidth:1,borderColor:colors.line,borderRadius:14,paddingHorizontal:13,flexDirection:'row-reverse',alignItems:'center',marginBottom:13},searchInput:{flex:1,paddingHorizontal:8,color:colors.text,fontSize:12},help:{fontSize:10.5,color:colors.muted,textAlign:'center',marginTop:8},
 carCard:{flexDirection:'row-reverse',alignItems:'center',gap:12},carIcon:{width:48,height:48,borderRadius:15,backgroundColor:colors.primarySoft,alignItems:'center',justifyContent:'center'},plate:{fontSize:12,color:colors.primary,fontWeight:'900',textAlign:'right',marginTop:7},parkingLabel:{fontSize:9,color:colors.muted},parking:{fontSize:13,color:colors.text,fontWeight:'900',textAlign:'center',marginTop:5},orderTop:{flexDirection:'row',justifyContent:'space-between',marginBottom:12},orderType:{fontSize:12,color:colors.primary,fontWeight:'900'},orderItems:{fontSize:12,color:colors.muted,textAlign:'right',lineHeight:20,marginTop:7},orderBottom:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginTop:13,paddingTop:12,borderTopWidth:1,borderTopColor:colors.line},orderTotal:{fontSize:16,color:colors.text,fontWeight:'900'},expenseTotal:{alignItems:'center',paddingVertical:22},expenseBig:{fontSize:28,color:colors.red,fontWeight:'900',marginTop:8},expenseRow:{minHeight:72,backgroundColor:colors.white,borderRadius:16,padding:13,marginBottom:9,flexDirection:'row-reverse',alignItems:'center',gap:10,...shadow},expenseIcon:{width:40,height:40,borderRadius:12,backgroundColor:colors.primarySoft,alignItems:'center',justifyContent:'center'},expenseAmount:{fontSize:13,color:colors.red,fontWeight:'900'},empty:{alignItems:'center',paddingVertical:55},emptyIcon:{fontSize:35,color:colors.line,marginBottom:10},
 bottomNav:{position:'absolute',bottom:0,left:0,right:0,height:75,backgroundColor:colors.white,borderTopWidth:1,borderTopColor:colors.line,flexDirection:'row-reverse',alignItems:'center',justifyContent:'space-around'},tab:{alignItems:'center',minWidth:60},tabIcon:{fontSize:20,color:colors.muted},tabText:{fontSize:9.5,color:colors.muted,marginTop:4},tabActive:{color:colors.primary,fontWeight:'900'},shade:{position:'absolute',top:0,left:0,right:0,bottom:0,backgroundColor:'rgba(6,29,35,.48)'},sheet:{position:'absolute',left:0,right:0,bottom:0,maxHeight:'88%',backgroundColor:colors.white,borderTopLeftRadius:25,borderTopRightRadius:25,padding:19,paddingBottom:28},sheetHandle:{width:42,height:4,borderRadius:3,backgroundColor:colors.line,alignSelf:'center',marginBottom:11},sheetHead:{flexDirection:'row',justifyContent:'space-between',marginBottom:16},sheetTitle:{fontSize:18,fontWeight:'900',color:colors.text},close:{fontSize:28,color:colors.muted},chooseRow:{minHeight:68,borderRadius:15,padding:11,flexDirection:'row-reverse',alignItems:'center',gap:11,marginBottom:7,borderWidth:1,borderColor:colors.line},chooseActive:{backgroundColor:colors.primarySoft,borderColor:'#C7E0E5'},selected:{fontSize:18,color:colors.green,fontWeight:'900'},field:{flex:1,marginBottom:13},fieldLabel:{fontSize:10.5,color:colors.muted,textAlign:'right',marginBottom:6},input:{height:46,borderWidth:1,borderColor:colors.line,borderRadius:13,backgroundColor:colors.canvas,paddingHorizontal:12,color:colors.text,fontSize:12},fieldsRow:{flexDirection:'row-reverse',gap:10},toggleRow:{minHeight:53,flexDirection:'row-reverse',alignItems:'center',justifyContent:'space-between',marginBottom:11},toggle:{width:46,height:26,borderRadius:14,backgroundColor:colors.line,padding:3},toggleOn:{backgroundColor:colors.primary},knob:{width:20,height:20,borderRadius:10,backgroundColor:colors.white,alignSelf:'flex-end'},knobOn:{alignSelf:'flex-start'},chips:{flexDirection:'row-reverse',flexWrap:'wrap',gap:7,marginBottom:14},chip:{borderWidth:1,borderColor:colors.line,borderRadius:20,paddingHorizontal:12,paddingVertical:8},chipActive:{backgroundColor:colors.primary,borderColor:colors.primary},chipText:{fontSize:10.5,color:colors.text,fontWeight:'700'},chipTextActive:{color:colors.white}
});
